replicaCount: 1

image:
  repository: ponaik/paymentservice
  pullPolicy: IfNotPresent
  tag: "1.1.2"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
  hosts:
    - host: payment.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Application Specific Configuration
config:
  springApplicationName: "PaymentService"
  mongoUri: "mongodb://payment-mongo:27017/payments"
  kafkaBootstrapServers: "kafka:9092"
  keycloakIssuerUri: "http://keycloak:8080/realms/UserService"
  openapiOauthIssuerUri: "http://keycloak.local/realms/UserService"
  otlpTracingEndpoint: "http://opentelemetry-collector.monitoring.svc.cluster.local:4318/v1/traces"
  otlpLoggingEndpoint: "http://opentelemetry-collector.monitoring.svc.cluster.local:4318/v1/logs"
  otlpMetricsEndpoint: "http://opentelemetry-collector.monitoring.svc.cluster.local:4318/v1/metrics"

# Full Probe Configuration
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 20
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 10