apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.config.springSecurityOauth2IssuerUri | quote }}
  USERSERVICE_BASEURL: {{ .Values.config.userServiceBaseUrl | quote }}
  ORDERSERVICE_BASEURL: {{ .Values.config.orderServiceBaseUrl | quote }}
  PAYMENTSERVICE_BASEURL: {{ .Values.config.paymentServiceBaseUrl | quote }}
  NETWORK_AUTH_SERVICE_BASE_URL: {{ .Values.config.networkAuthServiceBaseUrl | quote }}
  OPENAPI_OAUTH_ISSUER_URI: {{ .Values.config.openapiOauthIssuerUri | quote }}
  MANAGEMENT_OTLP_TRACING_ENDPOINT: {{ .Values.config.otlpTracingEndpoint | quote }}
  MANAGEMENT_OTLP_LOGGING_ENDPOINT: {{ .Values.config.otlpLoggingEndpoint | quote }}
  MANAGEMENT_OTLP_METRICS_EXPORT_URL: {{ .Values.config.otlpMetricsEndpoint | quote }}