apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- toYaml .Values.secret.encryptedData | nindent 4 }}
  template:
    metadata:
      name: {{ .Values.secret.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque