apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: order-auth-secrets
  namespace: default
spec:
  encryptedData:
    password: AgBAXLcvw5Ubz9X+HgzJNtxQfor17cdLumi4VtzgUFslQj1qv2tR9rGZEJowJ7JMxF4ZN//5KuP20qEWBOz0WYNtLjpmZG/Lwd7j4O2soaqcLjl4j7vvsmHuAtpiSpnVwWrUewHUOT8975/2B/jlmVHshvijPmRaqaLq10p9/1ui2l2Q2G5btCRf5gKnyB1dSCiRkoiULoc1KWCvgk995DuT93UFEd6G9RStAvgy/aznE6nYrPK/EfN+iL7mH+JIWFdR40mlFlSw/v3zM1GphkunJ6fR4vPXDKrQg0826sVcRS4+RvomgLf2Z9pHwnjoKdDNGUj24BsooZQkjcMFl/Sh5AIwxAGHHTjbv9WvKwXAqsHGy2MN5PXeRra2add21YjfHumFH0VOzXNMKA9ppkLy0B1ton6fYK0YQh9+wkGoGqUgZa8T4lUrBq69gXSXF1P/a0HtiJaus729aUPfs3PddNCt0iH3qRrfUO4/EW6LTenO/OOgP+7ZEDT8Qpd2KcJkgolM/xEwa4F/9lWRYwWbRo/Mhv0MVDILyAJl9t2VscNMW5YYlEQZSYgsymDdZetOHMRCYLweEyCIrLSAdwWGG63gHCT96XUruZZKgZTGM6WaYb/kHwkvNP1UkVTnYWz0aYpyjTrCaoJmxedLV+TCDiJDaeWxkf/Y2klVtJ04IAacnFzRK1EL2yj1FT8fJcUOKOcsH5+AT94mJFC6LQbyZQfEiXc=
    username: AgANnnJ7msAjcduCbnDrIndJcLXR4OpcOJtu6lRZXGaqWa7/XDD6vA86X507XImOpcgOMo504/Di8mZkQ/OfybXcshCRWTNFQTc2zSeJz8C+4RR+EisOvPTybgsFVDOsDn8GEMHzJQvm62ZM2rPaK7kaQ/oaOS1SXOOBoZc8ojSYDcVoL6TN19PNSlM3bbnbJPi2HeVB52wEZSfM02Q6Rbumt3mEYr5KdRxV4RS+i/M2hUK0dRM5IIXTAQXocFFL4BQQdOUG1G4ywAYbWWqvxgFO1x/bTcIwZIYiYOjVNfcxQpGu4qHYIE1q4zHIYbAVrJp5lMBK2V/a0m4dG27nC32sCoEaekJ7Tykdak0Z5HYb68rHRIgFmWXhIwsF2M3uZuoKo6O5dPnlz/42KREOlkSgl/68Nbq56iMZ+XFx8UMMwzS/fuZBGIzi7m3uud1DupjIcpp0YfB+0hiX3XTtWliJpjTEzSf2Inxgo4NH7f4LEEWILhn0LCHTHr1LHXRfJfUWcQ6MZmg1YmeTzkfPYhQJcWB5q4ljDo5lJ0pCEuh25nZmY+bkuCaZYswqCKW4rFETduEg6XsepnxVtMWHeX73CpFGV5mPaznQHNsWtmPpbs4wlOp5ekgyNjaAuxCKTEdVk0ckOpnAW8n9eKBszxr6iA1ghuZ5po9yaMp+fTqaqbdf2HUyaGB8xgO63f7B2mNWIp6yieBRjA==
  template:
    metadata:
      name: order-auth-secrets
      namespace: default
    type: kubernetes.io/basic-auth
