apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db-new
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  storage:
    size: 1Gi
    storageClass: standard

  bootstrap:
    initdb:
      database: orders
      owner: app_user
      secret:
        name: order-auth-secrets