apiVersion: v1
kind: Secret
metadata:
  name: gateway-credentials
type: Opaque
stringData:
  GATEWAY_CLIENT_ID: user-registration-service
  GATEWAY_CLIENT_SECRET: KGpNCvNPwLhznehdF8qpwgf3DDEuf3pO
  AUTH_CLIENT_ID: user-service-rest-api
  AUTH_CLIENT_SECRET: JvBGFKPxxLzEoldNjyLZHtyEmF3HBrky