apiVersion: v1
kind: Secret
metadata:
  name: orderservice-env-secrets
type: Opaque
stringData:
  ORDERSERVICE_DB_SCHEMA: orderdb
  ORDERSERVICE_DB_USER: prod
  ORDERSERVICE_DB_PASS: evensecreterpassword