apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paymentservice.fullname" . }}-config
  labels:
    {{- include "paymentservice.labels" . | nindent 4 }}
data:
  SPRING_APPLICATION_NAME: {{ .Values.config.springApplicationName | quote }}
  SPRING_MONGODB_URI: {{ .Values.config.mongoUri | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.config.keycloakIssuerUri | quote }}
  OPENAPI_OAUTH_ISSUER_URI: {{ .Values.config.openapiOauthIssuerUri | quote }}
  MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: {{ .Values.config.otlpTracingEndpoint | quote }}
  MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT: {{ .Values.config.otlpTracingEndpoint | quote }}