apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentservice.fullname" . }}
  labels:
    {{- include "paymentservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "paymentservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "paymentservice.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "paymentservice.fullname" . }}-config
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- else }}
            requests:
              memory: {{ .Values.global.resources.requests.memory | quote }}
              cpu: {{ .Values.global.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.global.resources.limits.memory | quote }}
              cpu: {{ .Values.global.resources.limits.cpu | quote }}
                      {{- end }}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.global.javaOptions | quote }}