apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "userservice.fullname" . }}
  labels:
    {{- include "userservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "userservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "userservice.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "userservice.fullname" . }}-config
          env:
            - name: USERSERVICE_DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: USERSERVICE_DB_SCHEMA
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: USERSERVICE_DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: USERSERVICE_DB_PASS
            - name: JAVA_OPTS
              value: {{ .Values.global.javaOptions | quote }}

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          resources:
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- else }}
            requests:
              memory: {{ .Values.global.resources.requests.memory | quote }}
              cpu: {{ .Values.global.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.global.resources.limits.memory | quote }}
              cpu: {{ .Values.global.resources.limits.cpu | quote }}
            {{- end }}