apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orderservice.fullname" . }}-config
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.datasourceUrl | quote }}
  USERSERVICE_BASEURL: {{ .Values.config.userServiceBaseUrl | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.config.keycloakIssuerUri | quote }}
  SWAGGER_UI_AUTHORIZATION_ISSUER_URI: {{ .Values.config.swaggerAuthIssuerUri | quote }}