apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orderservice.fullname" . }}-config
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.datasourceUrl | quote }}
  USERSERVICE_BASEURL: {{ .Values.config.userServiceBaseUrl | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.config.keycloakIssuerUri | quote }}
  OPENAPI_OAUTH_ISSUER_URI: {{ .Values.config.openapiOauthIssuerUri | quote }}
  MANAGEMENT_OTLP_TRACING_ENDPOINT: {{ .Values.config.otlpTracingEndpoint | quote }}
  MANAGEMENT_OTLP_LOGGING_ENDPOINT: {{ .Values.config.otlpLoggingEndpoint | quote }}
  MANAGEMENT_OTLP_METRICS_EXPORT_URL: {{ .Values.config.otlpMetricsEndpoint | quote }}
  LOGGING_FILE_NAME: {{ .Values.config.loggingFileName | quote }}