apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orderservice.fullname" . }}
  labels:
    {{- include "orderservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orderservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orderservice.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "orderservice.fullname" . }}-config
          env:
            # Database Secrets
            - name: ORDERSERVICE_DB_SCHEMA
              value: "orders"
            - name: ORDERSERVICE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: username
            - name: ORDERSERVICE_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: password

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}