apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: paymentservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: ponaik/paymentservice:1.0.0
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          env:
            - name: SPRING_APPLICATION_NAME
              value: PaymentService
            # MongoDB Config (Refers to the Service name 'payment-mongo')
            - name: SPRING_MONGODB_URI
              value: mongodb://payment-mongo:27017/payments
            # Kafka Config (Refers to the Service name 'kafka')
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            # Security & Oauth (Assuming values are provided via ConfigMap or Secret)
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak:8080/realms/UserService"
            - name: SWAGGER_UI_OAUTH_ISSUER_URI
              value: "http://keycloak.local/realms/UserService"

