apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-config
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  KC_HOSTNAME: {{ .Values.config.hostname | quote }}
  KC_PROXY: {{ .Values.config.proxyMode | quote }}
  KC_DB: {{ .Values.config.dbName | quote }}