apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            {{- toYaml .Values.image.command | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "keycloak.fullname" . }}-config
          env:
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ include "keycloak.fullname" . }}-postgres:5432/${KC_DB_NAME}"
            - name: KC_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: KEYCLOAK_POSTGRES_DB
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: KEYCLOAK_POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: KEYCLOAK_POSTGRES_PASSWORD
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: JAVA_OPTS
              value: {{ .Values.global.javaOptions | quote }}

          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- else }}
            requests:
              memory: {{ .Values.global.resources.requests.memory | quote }}
              cpu: {{ .Values.global.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.global.resources.limits.memory | quote }}
              cpu: {{ .Values.global.resources.limits.cpu | quote }}
            {{- end }}