{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "keycloak.fullname" . }}-postgres*/}}
{{/*  labels:*/}}
{{/*    app: {{ include "keycloak.fullname" . }}-postgres*/}}
{{/*spec:*/}}
{{/*  ports:*/}}
{{/*    - port: 5432*/}}
{{/*      targetPort: 5432*/}}
{{/*      name: postgres*/}}
{{/*  selector:*/}}
{{/*    app: {{ include "keycloak.fullname" . }}-postgres*/}}
{{/*---*/}}
{{/*apiVersion: apps/v1*/}}
{{/*kind: StatefulSet*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "keycloak.fullname" . }}-postgres*/}}
{{/*  labels:*/}}
{{/*    app: {{ include "keycloak.fullname" . }}-postgres*/}}
{{/*spec:*/}}
{{/*  serviceName: "postgres"*/}}
{{/*  replicas: 1*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app: {{ include "keycloak.fullname" . }}-postgres*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      labels:*/}}
{{/*        app: {{ include "keycloak.fullname" . }}-postgres*/}}
{{/*    spec:*/}}
{{/*      containers:*/}}
{{/*        - name: postgres*/}}
{{/*          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"*/}}
{{/*          ports:*/}}
{{/*            - containerPort: 5432*/}}
{{/*              name: postgres*/}}
{{/*          env:*/}}
{{/*            - name: POSTGRES_DB*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  name: {{ .Values.secret.name }}*/}}
{{/*                  key: KEYCLOAK_POSTGRES_DB*/}}
{{/*            - name: POSTGRES_USER*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  name: {{ .Values.secret.name }}*/}}
{{/*                  key: KEYCLOAK_POSTGRES_USER*/}}
{{/*            - name: POSTGRES_PASSWORD*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  name: {{ .Values.secret.name }}*/}}
{{/*                  key: KEYCLOAK_POSTGRES_PASSWORD*/}}

{{/*          # Basic Postgres health check*/}}
{{/*          livenessProbe:*/}}
{{/*            exec:*/}}
{{/*              command: ["sh", "-c", "exec pg_isready -U $POSTGRES_USER -h 127.0.0.1 -p 5432"]*/}}
{{/*            initialDelaySeconds: 30*/}}
{{/*            periodSeconds: 10*/}}
{{/*            timeoutSeconds: 5*/}}
{{/*          readinessProbe:*/}}
{{/*            exec:*/}}
{{/*              command: ["sh", "-c", "exec pg_isready -U $POSTGRES_USER -h 127.0.0.1 -p 5432"]*/}}
{{/*            initialDelaySeconds: 5*/}}
{{/*            periodSeconds: 10*/}}
{{/*            timeoutSeconds: 5*/}}

{{/*          volumeMounts:*/}}
{{/*            - name: postgres-data*/}}
{{/*              mountPath: /var/lib/postgresql/data*/}}
{{/*  volumeClaimTemplates:*/}}
{{/*    - metadata:*/}}
{{/*        name: postgres-data*/}}
{{/*      spec:*/}}
{{/*        accessModes: ["ReadWriteOnce"]*/}}
{{/*        storageClassName: {{ .Values.postgres.storage.className | quote }}*/}}
{{/*        resources:*/}}
{{/*          requests:*/}}
{{/*            storage: {{ .Values.postgres.storage.size }}*/}}